---
fullnameOverride: api-gateway

ingress:
  enabled: true

  # Default annotations
  annotations: {}

  # Default ingress class name
  className: nginx-external

  # Default TLS settings
  tls:
    enabled: true
    cluster_issuer: letsencrypt-prod

  # Default authorizer
  authorizer:
    uri: http://iam-authorizer.iam.svc.cluster.local:5000/authorize

  # Default backend
  service:
    name: nginx-ingress
    port: 80

  # Routing rules
  rules:
