provider:
  name: aws
env:
  - name: AWS_DEFAULT_REGION
    value: eu-central-1 # change to region where EKS is installed
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /.aws/credentials
extraVolumes:
  - name: aws-credentials
    secret:
      secretName: external-dns 
extraVolumeMounts:
  - name: aws-credentials
    mountPath: /.aws
    readOnly: true

extraArgs:
  - --domain-filter=chene-factory.com 
  - --aws-zone-type=public