---
name: devops-demo
namespace: vi-dev
contour: vi-dev
hostsuffix: vi-dev
version: REPLACE

imagePullSecrets:
  - name: gitlab-registry

groups:
  main:
    apps:
      devops-demo:
        replicas: 2
        podAntiAffinity:
          app: devops-demo
        securityContext:
          runAsUser: 1002
          runAsGroup: 1002
          fsGroup: 1002
        strategyType: RollingUpdate
        reloader: true
        image: 851725552187.dkr.ecr.eu-central-1.amazonaws.com/dev-vi-ecr
        targetport: 3000
        dapr:
          enabled: false
        daprTracing:
          enabled: false
        probes: true
        probe:
          liveness: /orders
          readiness: /orders
          startup: /orders
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 300Mi
serviceAccount:
  enabled: true
  permissions:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
        - update
    - apiGroups:
        - ""
      resources:
        - services
      verbs:
        - get
        - list
        - update
    - apiGroups:
        - ""
      resources:
        - pods/log
      verbs:
        - get
        - list
        - update
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
