---
global:
  additionalLabels: {}
  # TODO alex k, enable in the next MR
  # addPrometheusAnnotations: true # Add prometheus annotations to all resources. :8083/metrics
  # metrics:
  #   enabled: true
crds:
  install: true
createClusterRoles: true
configs:
  params:
    controller.repo.server.timeout.seconds: 5
  cm:
    admin.enabled: true
    timeout.reconciliation: 5s
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import,
      secrets+age-import-kubernetes, secrets,secrets+literal, https

server:
  extensions:
    enabled: true
  extraArgs:
      - --insecure
  ingress:
    enabled: false


repoServer:
  env:
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_CURL_PATH
      value: /custom-tools/curl
    - name: HELM_SECRETS_SOPS_PATH
      value: /custom-tools/sops
    - name: HELM_SECRETS_VALS_PATH
      value: /custom-tools/vals
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /custom-tools/kubectl
    - name: HELM_SECRETS_BACKEND
      value: sops
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "false"
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt
    - name: SOPS_AGE_RECIPIENTS
      value: public-key
  initContainers:
    - args:
        - |
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v$${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

          wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
          wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v$${SOPS_VERSION}/sops-v$${SOPS_VERSION}.linux
          wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v$${KUBECTL_VERSION}/bin/linux/amd64/kubectl

          wget -qO- https://github.com/helmfile/vals/releases/download/v$${VALS_VERSION}/vals_$${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;
          
          cat <<'EOF' | sed -i '1 r /dev/stdin' /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh
          mkdir -p -m 700 /tmp/helm-secrets-tmp
          find /tmp/helm-secrets-tmp/ -type d -mmin +20 -print0 | xargs -0 rm -rf
          export HELM_SECRETS_DEC_DIR=$(mktemp -d -p /tmp/helm-secrets-tmp)
          EOF

          cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm

          chmod +x /custom-tools/*
      command:
        - sh
        - -ec
      env:
        - name: HELM_SECRETS_VERSION
          value: "4.5.1"
        - name: KUBECTL_VERSION
          value: 1.26.1
        - name: VALS_VERSION
          value: 0.24.0
        - name: SOPS_VERSION
          value: 3.7.3
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      name: download-tools
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
    - mountPath: /usr/local/sbin/helm
      name: custom-tools
      subPath: helm
    - mountPath: /.config/sops/age/keys.txt
      name: age-secret
      subPath: keys.txt
  volumes:
    - emptyDir: {}
      name: custom-tools
    - name: age-secret
      secret:
        secretName: age-secret
        items:
        - key: keys.txt
          path: keys.txt