---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-charts
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gmukhigulashvili/devops-assignment.git
        revision: master
        files:
          - path: "helm/values/helm-chart/**/deployment.yaml"
  template:
    metadata:
      name: '{{"{{"}}name{{"}}"}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - applyOutOfSyncOnly=true
      revisionHistoryLimit: 5
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[].namespaceSelector[]
            - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
            - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jqPathExpressions:
            - ..|.priority?
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - '/spec/template/metadata/annotations/checksum~1webserver-secret-key'
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - '/spec/template/metadata/annotations/checksum~1config'
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - '/spec/template/metadata/annotations/checksum~1secret'
        - group: apps
          kind: Deployment
          jsonPointers:
            - '/spec/template/metadata/annotations/checksum~1webserver-secret-key'
      sources:
        - chart: '{{"{{"}}chart{{"}}"}}'
          helm:
            releaseName: '{{"{{"}}name{{"}}"}}'
            valueFiles:
              - $values/helm/values/helm-chart/{{"{{"}}name{{"}}"}}/values.yaml
              - $values/helm/values/helm-chart/{{"{{"}}name{{"}}"}}/secrets.enc.yaml
          repoURL: '{{"{{"}}repoURL{{"}}"}}'
          targetRevision: '{{"{{"}}targetRevision{{"}}"}}'
        - ref: values
          repoURL: https://github.com/gmukhigulashvili/devops-assignment.git
          targetRevision: master
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{"{{"}}namespace{{"}}"}}'
