name: Build and Push Docker Image to Private ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get commit hash
      run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Get timestamp
      run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t $ECR_REGISTRY/dev-vi-ecr:$commit_hash-$timestamp .

    - name: Tag Docker image
      run: docker tag $ECR_REGISTRY/dev-vi-ecr:$commit_hash-$timestamp $ECR_REGISTRY/dev-vi-ecr:latest 

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/dev-vi-ecr:latest
        docker push $ECR_REGISTRY/dev-vi-ecr:$commit_hash-$timestamp

    - name: Log out from Docker
      if: always()
      run: docker logout
