name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
           ${{ secrets.DOCKER_USERNAME }}/vi-app:latest
           ${{ secrets.DOCKER_USERNAME }}/vi-app:${{ github.sha }}

    - name: Clone vi-values repository
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/gmukhigulashvili/vi-values.git
        cd vi-values/app1
        echo "version: ${{ github.sha }}" > version.yaml

    - name: Commit and push changes
      run: |
        cd vi-values
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add app1/version.yaml
        git commit -m "Update version.yaml with commit SHA ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/gmukhigulashvili/vi-values.git HEAD:main
