name: Build and Push Docker Image to Private ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Log out from Docker (if previously logged in)
      run: docker logout
    
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        registry: 423067824323.dkr.ecr.eu-west-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t 423067824323.dkr.ecr.eu-west-1.amazonaws.com/dev-vi-ecr:latest .

    - name: Tag Docker image
      run: |
        docker tag 423067824323.dkr.ecr.eu-west-1.amazonaws.com/dev-vi-ecr:latest 423067824323.dkr.ecr.eu-west-1.amazonaws.com/dev-vi-ecr:${{ github.sha }}


    - name: Push Docker image to ECR
      run: |
        docker push 423067824323.dkr.ecr.eu-west-1.amazonaws.com/dev-vi-ecr:latest
        docker push 423067824323.dkr.ecr.eu-west-1.amazonaws.com/dev-vi-ecr:${{ github.sha }}
